Support .browserslistrc
azu/eslint-plugin-typescript-compat pull request #12
Opened 2023-08-21 13:14 UTC by jakubdatawrapper

### Steps to reproduce

1. Add a `.browserslistrc` file to your project:

    ```
    ie 11
    ```

2. Add a TS file to your project that uses features not available in IE11:

    ```ts
    const a = [1, 2, 3];
    a.includes(2);
    ```

3. Configure eslint with `eslint-plugin-typescript-compat`. Notice that the `browserslist` setting is not defined: 

    ```js
    {
        "extends": ["plugin:typescript-compat/recommended"],
        "env": {
          "browser": true
        },
        "parserOptions": {
          "project": "./tsconfig.json"
        }
    }
    ```

4. Run eslint and see that it doesn't show an error that `Array.prototype.includes()` is not supported in IE11.

### Problem

The problem is that when there is no browserslist defined in .eslintrc like in the above example, then `eslint-plugin-typescript-compat` uses the value `"defaults"`, instead of reading a `.browserslistrc` file.

### Solution

Don't set a default browserslist value. This makes the `browserslist` library automatically read a `.browserslistrc` file. If `.browserslistrc` doesn't exist, then `browserslist` will automatically use `"defaults"`. It doesn't need to be passed by eslint-plugin-typescript-compat.

2023-08-21 15:10 UTC, azu requested changes
Thanks for PR!

It looks like that You need to change Options type.

```diff
export type Options = [
    {
-        browserslist: string | string[];
+        browserslist?: string | string[];
        polyfills: string[];
    }
];
```

2023-08-22 00:34 UTC, azu approved these changes
LGTM

Thanks!

2023-08-22 00:34 UTC, merged

2023-08-22 00:38 UTC, azu commented
https://github.com/azu/eslint-plugin-typescript-compat/releases/tag/v1.0.2 🎉

2023-08-22 09:34 UTC, jakubdatawrapper commented
Fantastic, thanks for the review!